import type { CertificateConfig } from './types';

const person = (name: string) => [
  { path: `${name}.firstName`, label: `${name} First Name` },
  { path: `${name}.lastName`, label: `${name} Last Name` },
];

export const certificateConfigs: CertificateConfig[] = [
  {
    key: 'baptismal',
    routePath: '/baptismal',
    apiModule: 'baptismal',
    certificateType: 'baptismal',
    title: 'Baptismal Certificates',
    subtitle: 'Manage baptismal certificate records.',
    listTitle: 'Baptismal Certificates',
    searchEnabled: true,
    fields: [
      { path: 'firstName', label: 'First Name' },
      { path: 'lastName', label: 'Last Name' },
      { path: 'address', label: 'Address' },
      { path: 'birthDate', label: 'Birth Date', type: 'date' },
      { path: 'occasionDate', label: 'Occasion Date', type: 'date' },
      ...person('parent1'),
      ...person('parent2'),
      ...person('sponsor1'),
      ...person('sponsor2'),
      ...person('celebrantPriest'),
      { path: 'bookNumber', label: 'Book Number', type: 'number' },
      { path: 'pageNumber', label: 'Page Number', type: 'number' },
    ],
    defaultValues: {
      certificateType: 'baptismal',
      firstName: '',
      lastName: '',
      address: '',
      birthDate: '',
      occasionDate: '',
      parent1: { firstName: '', lastName: '' },
      parent2: { firstName: '', lastName: '' },
      sponsor1: { firstName: '', lastName: '' },
      sponsor2: { firstName: '', lastName: '' },
      celebrantPriest: { firstName: '', lastName: '' },
      bookNumber: 0,
      pageNumber: 0,
    },
    nameFromRecord: (record) => `${record.firstName ?? ''} ${record.lastName ?? ''}`.trim(),
    secondaryFromRecord: (record) => String(record.occasionDate ?? ''),
  },
  {
    key: 'confirmation',
    routePath: '/confirmation',
    apiModule: 'confirmation',
    certificateType: 'confirmation',
    title: 'Confirmation Certificates',
    subtitle: 'Manage confirmation certificate records.',
    listTitle: 'Confirmation Certificates',
    searchEnabled: true,
    fields: [
      { path: 'firstName', label: 'First Name' },
      { path: 'lastName', label: 'Last Name' },
      { path: 'occasionDate', label: 'Occasion Date', type: 'date' },
      ...person('parent1'),
      ...person('parent2'),
      ...person('sponsor1'),
      ...person('sponsor2'),
      ...person('celebrantPriest'),
      { path: 'bookNumber', label: 'Book Number', type: 'number' },
      { path: 'pageNumber', label: 'Page Number', type: 'number' },
    ],
    defaultValues: {
      certificateType: 'confirmation',
      firstName: '',
      lastName: '',
      occasionDate: '',
      parent1: { firstName: '', lastName: '' },
      parent2: { firstName: '', lastName: '' },
      sponsor1: { firstName: '', lastName: '' },
      sponsor2: { firstName: '', lastName: '' },
      celebrantPriest: { firstName: '', lastName: '' },
      bookNumber: 0,
      pageNumber: 0,
    },
    nameFromRecord: (record) => `${record.firstName ?? ''} ${record.lastName ?? ''}`.trim(),
    secondaryFromRecord: (record) => String(record.occasionDate ?? ''),
  },
  {
    key: 'death',
    routePath: '/death',
    apiModule: 'death',
    certificateType: 'death',
    title: 'Death Certificates',
    subtitle: 'Manage death certificate records.',
    listTitle: 'Death Certificates',
    searchEnabled: true,
    fields: [
      { path: 'firstName', label: 'First Name' },
      { path: 'lastName', label: 'Last Name' },
      { path: 'address', label: 'Address' },
      { path: 'age', label: 'Age' },
      { path: 'burialDate', label: 'Burial Date', type: 'date' },
      { path: 'deathDate', label: 'Death Date', type: 'date' },
      { path: 'burialPlace', label: 'Burial Place' },
      { path: 'sacraments', label: 'Sacraments' },
      ...person('survivors'),
      ...person('celebrantPriest'),
      { path: 'bookNumber', label: 'Book Number', type: 'number' },
      { path: 'pageNumber', label: 'Page Number', type: 'number' },
    ],
    defaultValues: {
      firstName: '',
      lastName: '',
      address: '',
      age: '',
      burialDate: '',
      deathDate: '',
      burialPlace: '',
      sacraments: '',
      survivors: { firstName: '', lastName: '' },
      celebrantPriest: { firstName: '', lastName: '' },
      bookNumber: 0,
      pageNumber: 0,
    },
    nameFromRecord: (record) => `${record.firstName ?? ''} ${record.lastName ?? ''}`.trim(),
    secondaryFromRecord: (record) => String(record.burialDate ?? ''),
  },
  {
    key: 'marriage',
    routePath: '/marriage',
    apiModule: 'marriage',
    certificateType: 'marriage',
    title: 'Marriage Certifications',
    subtitle: 'Manage marriage certificate records.',
    listTitle: 'Marriage Certifications',
    fields: [
      ...person('bride'),
      ...person('groom'),
      ...person('sponsor1'),
      ...person('sponsor2'),
      ...person('celebrantPriest'),
      { path: 'licenseNumber', label: 'License Number' },
      { path: 'registryNumber', label: 'Registry Number' },
      { path: 'remarks', label: 'Remarks' },
      { path: 'occasionDate', label: 'Occasion Date', type: 'date' },
      { path: 'bookNumber', label: 'Book Number', type: 'number' },
      { path: 'pageNumber', label: 'Page Number', type: 'number' },
    ],
    defaultValues: {
      bride: { firstName: '', lastName: '' },
      groom: { firstName: '', lastName: '' },
      sponsor1: { firstName: '', lastName: '' },
      sponsor2: { firstName: '', lastName: '' },
      celebrantPriest: { firstName: '', lastName: '' },
      licenseNumber: '',
      registryNumber: '',
      remarks: '',
      occasionDate: '',
      bookNumber: 0,
      pageNumber: 0,
    },
    nameFromRecord: (record) => {
      const bride = (record.bride as { firstName?: string; lastName?: string } | undefined) ?? {};
      const groom = (record.groom as { firstName?: string; lastName?: string } | undefined) ?? {};
      return `${bride.firstName ?? ''} ${bride.lastName ?? ''} + ${groom.firstName ?? ''} ${groom.lastName ?? ''}`.trim();
    },
    secondaryFromRecord: (record) => String(record.occasionDate ?? ''),
  },
];

export function getCertificateConfigByPath(pathname: string): CertificateConfig | undefined {
  return certificateConfigs.find((config) => pathname === config.routePath || pathname.startsWith(`${config.routePath}/`));
}

export function getCertificateConfigByKey(key: string): CertificateConfig | undefined {
  return certificateConfigs.find((config) => config.key === key);
}
